# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\add_fund.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFund(object):
    def setupUi(self, addFund):
        addFund.setObjectName("addFund")
        addFund.resize(621, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(addFund)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(addFund)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.fund_name = QtWidgets.QLineEdit(addFund)
        self.fund_name.setObjectName("fund_name")
        self.horizontalLayout_3.addWidget(self.fund_name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.duplicate_fund_warning = QtWidgets.QLabel(addFund)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicate_fund_warning.sizePolicy().hasHeightForWidth())
        self.duplicate_fund_warning.setSizePolicy(sizePolicy)
        self.duplicate_fund_warning.setVisible(False)
        self.duplicate_fund_warning.setStyleSheet("color: red; font-weight: bold;")
        self.duplicate_fund_warning.setWordWrap(True)
        self.duplicate_fund_warning.setProperty("leftMargin", 0)
        self.duplicate_fund_warning.setProperty("topMargin", 10)
        self.duplicate_fund_warning.setProperty("rightMargin", 0)
        self.duplicate_fund_warning.setProperty("bottomMargin", 10)
        self.duplicate_fund_warning.setObjectName("duplicate_fund_warning")
        self.horizontalLayout_5.addWidget(self.duplicate_fund_warning)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(addFund)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.initial_units = QtWidgets.QLineEdit(addFund)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initial_units.sizePolicy().hasHeightForWidth())
        self.initial_units.setSizePolicy(sizePolicy)
        self.initial_units.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.initial_units.setObjectName("initial_units")
        self.horizontalLayout_4.addWidget(self.initial_units)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.delete_fund = QtWidgets.QCheckBox(addFund)
        self.delete_fund.setEnabled(True)
        self.delete_fund.setObjectName("delete_fund")
        self.verticalLayout.addWidget(self.delete_fund)
        self.buttonBox = QtWidgets.QDialogButtonBox(addFund)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addFund)
        self.buttonBox.accepted.connect(addFund.accept) # type: ignore
        self.buttonBox.rejected.connect(addFund.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addFund)

    def retranslateUi(self, addFund):
        _translate = QtCore.QCoreApplication.translate
        addFund.setWindowTitle(_translate("addFund", "Add Fund"))
        self.label.setText(_translate("addFund", "Fund Name"))
        self.duplicate_fund_warning.setText(_translate("addFund", "Fund name already exists.Choose a different name"))
        self.label_2.setText(_translate("addFund", "Initial Units"))
        self.delete_fund.setText(_translate("addFund", "Delete Fund"))
