# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\unit_purchase_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unitPurchaseDialog(object):
    def setupUi(self, unitPurchaseDialog):
        unitPurchaseDialog.setObjectName("unitPurchaseDialog")
        unitPurchaseDialog.resize(704, 408)
        self.buttonBox = QtWidgets.QDialogButtonBox(unitPurchaseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-110, 360, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(unitPurchaseDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 610, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.fund_selector = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.fund_selector.setObjectName("fund_selector")
        self.horizontalLayout_3.addWidget(self.fund_selector)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.purchase_dollars = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purchase_dollars.sizePolicy().hasHeightForWidth())
        self.purchase_dollars.setSizePolicy(sizePolicy)
        self.purchase_dollars.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.purchase_dollars.setObjectName("purchase_dollars")
        self.horizontalLayout_4.addWidget(self.purchase_dollars)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.purchase_date = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purchase_date.sizePolicy().hasHeightForWidth())
        self.purchase_date.setSizePolicy(sizePolicy)
        self.purchase_date.setKeyboardTracking(False)
        self.purchase_date.setObjectName("purchase_date")
        self.horizontalLayout_2.addWidget(self.purchase_date)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.account_value = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.account_value.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_value.sizePolicy().hasHeightForWidth())
        self.account_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_value.setFont(font)
        self.account_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.account_value.setObjectName("account_value")
        self.horizontalLayout.addWidget(self.account_value)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.delete_purchase = QtWidgets.QCheckBox(unitPurchaseDialog)
        self.delete_purchase.setEnabled(True)
        self.delete_purchase.setGeometry(QtCore.QRect(240, 310, 201, 29))
        self.delete_purchase.setObjectName("delete_purchase")

        self.retranslateUi(unitPurchaseDialog)
        self.buttonBox.accepted.connect(unitPurchaseDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(unitPurchaseDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(unitPurchaseDialog)

    def retranslateUi(self, unitPurchaseDialog):
        _translate = QtCore.QCoreApplication.translate
        unitPurchaseDialog.setWindowTitle(_translate("unitPurchaseDialog", "Purchase Units"))
        self.label.setText(_translate("unitPurchaseDialog", "Fund Name"))
        self.label_3.setText(_translate("unitPurchaseDialog", "Dollars invested"))
        self.label_2.setText(_translate("unitPurchaseDialog", "Purchase Date"))
        self.label_4.setText(_translate("unitPurchaseDialog", "Account Value on Purchase Date "))
        self.delete_purchase.setText(_translate("unitPurchaseDialog", "Delete Purchase"))
