site_name: UnitTracker Documentation

theme: 
    name: material

nav:
  - 'Home': 'index.md'
  - 'Installation': 'installation.md'
  - 'Basics': 'basics.md'
  - 'Getting Started': 'getting_started.md'
  - 'Maintaining the Account': 'maintaining_the_account.md'
  - 'Appendix A - Commingled Iinvestments and Unitization': 'appendix_a.md'