site_name: UnitTracker Documentation

theme: 
    name: material

nav:
  - 'Home': 'index.md'
  - 'Installation': 'installation.md'
  - 'Basics': 'basics.md'
  - 'Getting Started': 'getting_started.md'
  - 'Maintaining the Account': 'maintaining_the_account.md'
  - 'Editing': 'editing.md'
  - 'Appendix A: Commingled Investments and Unitization': 'appendix_a.md'

markdown_extensions:
  - toc:
      permalink: "#"